# Project
version=11.0.0+1.21.4
group=com.illusivesoulworks.cherishedworlds
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Cherished Worlds
mod_author=Illusive Soulworks
mod_id=cherishedworlds
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/cherishedworlds/issues
sources_url=https://github.com/illusivesoulworks/cherishedworlds
description=Favorite/pin/bookmark certain worlds, which will always be at the top of the list and cannot be deleted.
minecraft_version_range=[1.21.4, 1.22)
minecraft_version_range_alt=~1.21.4

# Parchment
parchment_mc=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.10

# Forge
forge_version=54.1.0
forge_version_range=[54,)

# NeoForge
neoforge_version=21.4.123
neoforge_version_range=[21.4,)

# Publishing Options
cf_id=308240
cf_page=https://www.curseforge.com/minecraft/mc-mods/cherished-worlds
modrinth_id=3azQ6p0W
modrinth_page=https://modrinth.com/mod/cherished-worlds
release_type=release
release_versions=1.21.4
changelog_link=https://github.com/illusivesoulworks/cherishedworlds/blob/1.21.4/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/180/595/636793993834717165.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
