# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=10.0.2+1.21.1
group=com.illusivesoulworks.cherishedworlds
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Cherished Worlds
mod_author=Illusive Soulworks
mod_id=cherishedworlds
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/cherishedworlds/issues
sources_url=https://github.com/illusivesoulworks/cherishedworlds
description=Favorite/pin/bookmark certain worlds, which will always be at the top of the list and cannot be deleted.
minecraft_version_range=[1.21, 1.22)
minecraft_version_range_alt=~1.21

# Parchment
parchment_mc=1.21
parchment_version=2024.07.28

# Fabric
fabric_version=0.102.1+1.21.1
fabric_loader_version=0.15.11

# Forge
forge_version=52.0.3
forge_version_range=[51,)

# NeoForge
neoforge_version=21.1.1
neoforge_version_range=[21,)

# Publishing Options
cf_id=308240
cf_page=https://www.curseforge.com/minecraft/mc-mods/cherished-worlds
modrinth_id=3azQ6p0W
modrinth_page=https://modrinth.com/mod/cherished-worlds
release_type=release
release_versions=1.21,1.21.1
changelog_link=https://github.com/illusivesoulworks/cherishedworlds/blob/1.21.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/180/595/636793993834717165.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
