# Project
version=16.0.0+26.2
group=com.illusivesoulworks.cherishedworlds
java_version=25

# Common
minecraft_version=26.2
mod_name=Cherished Worlds
mod_author=Illusive Soulworks
mod_id=cherishedworlds
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/cherishedworlds/issues
sources_url=https://github.com/illusivesoulworks/cherishedworlds
description=Favorite/pin/bookmark certain worlds, which will always be at the top of the list and cannot be deleted.
minecraft_version_range=[26.2,)
minecraft_version_range_alt=~26.2

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# SpectreLib
spectrelib_version=0.22.0+26.2

# Fabric
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# Forge
forge_version=65.0.5
forge_version_range=[62,)

# NeoForge
neoforge_version=26.2.0.23-beta
neoforge_version_range=[26.2,)

# Publishing Options
cf_id=308240
cf_page=https://www.curseforge.com/minecraft/mc-mods/cherished-worlds
modrinth_id=3azQ6p0W
modrinth_page=https://modrinth.com/mod/cherished-worlds
release_type=release
release_versions=26.2
changelog_link=https://github.com/illusivesoulworks/cherishedworlds/blob/26.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/180/595/636793993834717165.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
